// About text for Wes

export default 'Hi, thanks for visiting my site and taking the time to learn more about me. I\'m a passionate full-stack software engineer with over 14 years of professional engineering experience and 7 years in engineering management.<br><br>' +

'My expertise spans across the stack, driven by a commitment to creating impactful experiences in every project I am involved in. I have successfully led teams in developing feature-rich client-side applications using various JavaScript frameworks such as React, NextJS, Redux, Angular, Backbone, etc. My focus is on delivering applications that offer outstanding user experiences, both functionally and visually.<br><br>' +

'On the server side, I have led teams in architecting and developing highly performant, resilient, and scalable cloud-based distributed applications and services. I have experience developing in a multitude of languages including JavaScript, TypeScript, Solidity, Go, Java, Ruby, SQL / NoSQL, Bash, Python, and I am currently learning Rust.  The applications I\'ve been a part of building have served millions of users in production environments and processed millions of events per second with extremely low latency. I excel in identifying and addressing performance bottlenecks in both client and server applications, implementing robust performance testing, metrics, logging, and alerting infrastructure.<br><br>' +

'Over the past 7 years, I have immersed myself in the blockchain and crypto space, dedicating significant time to mastering the principles of decentralized applications, primarily within the Ethereum ecosystem and layer 2 chains, though I also have experience developing with other chains such as Solana and Cosmos. I am a strong advocate for decentralized and permissionless systems that empower users beyond traditional / centralized systems, aiming to democratize access to applications and services traditionally reserved for institutions or individuals with significant credentials and/or wealth.<br><br>' +

'As a user and developer in the Web3 space, I am committed to the long-term evolution and sustainability of these protocols and dApps. My goal is to help transform our online presence, returning ownership and control back to the individual.';